name: RedditNobility
version: ${project.version}
main: me.kingtux.redditnobility.RedditNobility
api-version: 1.13
authors: [ KingTux ]
description: The Reddit Nobility Core plugin
depend:
  - TuxCore
website: kingtux.me
